# -*- coding: utf-8 -*-
"""telegram_btc_bot

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1ZT071nAckhdiouDFGEzhT17a_udiFvLJ
"""

import requests
from telegram import Update
from telegram.ext import Updater, CommandHandler, MessageHandler, Filters, CallbackContext

# Replace with your Telegram bot token from BotFather
TELEGRAM_BOT_TOKEN = "YOUR_BOT_TOKEN_HERE"

# Coinbase API endpoints
API_URL_CAD = "https://api.coinbase.com/v2/prices/BTC-CAD/spot"
API_URL_AED = "https://api.coinbase.com/v2/prices/BTC-AED/spot"

def get_btc_price():
    """Fetches BTC price in CAD and AED from Coinbase API."""
    try:
        cad_price = requests.get(API_URL_CAD).json()["data"]["amount"]
        aed_price = requests.get(API_URL_AED).json()["data"]["amount"]
        return cad_price, aed_price
    except Exception as e:
        return None, None

def handle_message(update: Update, context: CallbackContext):
    """Responds to user messages."""
    text = update.message.text.lower()

    if text == "price":
        cad_price, aed_price = get_btc_price()
        if cad_price and aed_price:
            reply = f"💰 Bitcoin Prices:\n🇨🇦 CAD: ${cad_price}\n🇦🇪 AED: {aed_price} AED"
        else:
            reply = "⚠️ Error fetching BTC prices. Try again later."

        update.message.reply_text(reply)

def main():
    """Starts the bot."""
    updater = Updater(TELEGRAM_BOT_TOKEN, use_context=True)
    dp = updater.dispatcher

    # Handle messages (text)
    dp.add_handler(MessageHandler(Filters.text & ~Filters.command, handle_message))

    # Start the bot
    updater.start_polling()
    print("🚀 Bot is running... (Press Ctrl + C to stop)")
    updater.idle()

if __name__ == "__main__":
    main()